#!/usr/bin/zsh
rm -rf  te_st/
rails new te_st --database=postgresql \
                --skip-asset-pipeline \
                --skip-javascript \
                --skip-jbuilder \
                -m rails_template_/first_example.rb \
/
