source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.4'
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# SLIM
gem 'slim-rails'

# HttParty
gem 'httparty'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# JWT
gem 'jwt'

# Kaminari
gem 'kaminari'

# state machine
gem 'state_machines-activerecord'

# gem 'mini_magick', '~> 4.8'
gem 'russian', '~> 0.6.0'
gem 'annotate'
gem 'pry-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'shoulda-matchers'
  gem 'faker'
  gem 'timecop'
end
# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"




group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :test do
  gem 'database_cleaner-active_record'
end

group :development do
  gem 'web-console'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'concurrent-ruby'
